// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 35.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AppAssets {
  static const String package = 'manga_user';

  static const String background_jpg = 'images/bg/background.jpg';

  static const String bg_payment_png = 'images/bg/bg_payment.png';

  static const String ic_app_icon_png = 'images/icon/ic_app_icon.png';

  static const String ic_arrow_after_svg = 'images/icon/ic_arrow_after.svg';

  static const String ic_arrow_before_svg = 'images/icon/ic_arrow_before.svg';

  static const String ic_arrow_left_svg = 'images/icon/ic_arrow_left.svg';

  static const String ic_close_svg = 'images/icon/ic_close.svg';

  static const String ic_crown_svg = 'images/icon/ic_crown.svg';

  static const String ic_discover_svg = 'images/icon/ic_discover.svg';

  static const String ic_download_svg = 'images/icon/ic_download.svg';

  static const String ic_eye_svg = 'images/icon/ic_eye.svg';

  static const String ic_facebook_svg = 'images/icon/ic_facebook.svg';

  static const String ic_file_not_found_svg = 'images/icon/ic_file_not_found.svg';

  static const String ic_home_svg = 'images/icon/ic_home.svg';

  static const String ic_library_svg = 'images/icon/ic_library.svg';

  static const String ic_like_svg = 'images/icon/ic_like.svg';

  static const String ic_list_svg = 'images/icon/ic_list.svg';

  static const String ic_logo_png = 'images/icon/ic_logo.png';

  static const String ic_note_svg = 'images/icon/ic_note.svg';

  static const String ic_notification_svg = 'images/icon/ic_notification.svg';

  static const String ic_novel_svg = 'images/icon/ic_novel.svg';

  static const String ic_options_svg = 'images/icon/ic_options.svg';

  static const String ic_people_svg = 'images/icon/ic_people.svg';

  static const String ic_redo_svg = 'images/icon/ic_redo.svg';

  static const String ic_save_add_svg = 'images/icon/ic_save_add.svg';

  static const String ic_scroll_horizontal_svg = 'images/icon/ic_scroll_horizontal.svg';

  static const String ic_setting_svg = 'images/icon/ic_setting.svg';

  static const String ic_share_svg = 'images/icon/ic_share.svg';

  static const String ic_sort_svg = 'images/icon/ic_sort.svg';

  static const String ic_sroll_vertical_svg = 'images/icon/ic_sroll_vertical.svg';

  static const String ic_star_svg = 'images/icon/ic_star.svg';

  static const String ic_trash_svg = 'images/icon/ic_trash.svg';

  static const String ic_undo_svg = 'images/icon/ic_undo.svg';

  static const String ic_view_svg = 'images/icon/ic_view.svg';

  static const String ic_vip_crown_svg = 'images/icon/ic_vip_crown.svg';
}
